#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: ppm <python_file> [args...]"
    exit 1
fi

python_file="$1"
shift
additional_args="$@"

recipient_email="$PPM_EMAIL"

if [ -z "$recipient_email" ]; then
    echo "Error: Email address not set. Please set the PPM_EMAIL environment variable."
    exit 1
fi

temp_output=$(mktemp)

python "$python_file" "$@" 2>&1 | tee "$temp_output"
exit_status=${PIPESTATUS[0]}

output=$(cat "$temp_output")

rm "$temp_output"

subject=$( [ $exit_status -eq 0 ] && echo "Success: $python_file $additional_args" || echo "Error: $python_file $additional_args" )

log_file=$(echo "$output" | tac | grep -oP '\S+\.log' | head -n 1)

if [ -f "$log_file" ]; then
    echo -e "$output" | mailx -s "$subject" -A "$log_file" "$recipient_email"
else
    if [ -n "$log_file" ]; then
        output="$output\n\nWarning: Log file path found but the file does not exist: $log_file"
    fi
    echo -e "$output" | mailx -s "$subject" "$recipient_email"
fi
