#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: ppm <python_file> [args...]"
    exit 1
fi

python_file="$1"
shift

additional_args="$@"

# make sure you set this variable in your OS
recipient_email="$PPM_EMAIL"

if [ -z "$recipient_email" ]; then
    echo "Error: Email address not set. Please set the PPM_EMAIL environment variable."
    exit 1
fi

output=$(python "$python_file" "$@" 2>&1)

echo "$output"

exit_status=$?

if [ $exit_status -eq 0 ]; then
    subject="Success: Output of $python_file"
else
    subject="Error: Output of $python_file"
fi

# if your python script is building a log file and you want it in your email.
log_file=$(echo "$output" | grep -oP 'Log file: \K.*')

if [ -f "$log_file" ]; then
    log_content=$(cat "$log_file")
    email_content="$output\n\n$log_content"
else
    email_content="$output"
fi


if [ ! -z "$additional_args" ]; then
    email_content="$email_content\n\nAdditional arguments: $additional_args"
fi

# Additionaly you could put some error handling for the `mail` command, I have it setup already so it works for me just fine!
echo -e "$email_content" | mail -s "$subject" "$recipient_email"
